---
title: Projects overview
format: docx
date: 2025-02-04
author: Katrina
toc: false
toc-location: left
number-sections: false
---

<!-- ## Admin -->

<!-- -   Finance new code (both Una Europa, and VICI project) -->
<!--     -   e.g. Participants fee for Qi & Yuchen -->

<!-- ## Projects ongoing -->

### Mandarin question in laboratory phonology

-   Focus: Establish the tone–intonation relationship using traditional laboratory phonology approaches, with particular emphasis on individual variability in intonation realisation.

-   Serves as the foundation for further perception-related investigations.

#### Completed ✅

-   2024 Nov-Dec: record 8 people, initial analysis, prepare TAI abstract
-   2025 Jan-Mar: processing with LIBC interns
-   2025 May-June: TAI presentation; LIBC poster
-   2025 August: TAI proceeding
-   2025 Nov-Dec: collaboration meetings; record 7 people
-   2026 Jan: processing new recording with LIBC interns

**Side-products**

-   Manual for segmentation (specifically for this task, but could potentially be expanded with other user cases) - 🧐 Perhaps ask your intern to accummulate some cases!
-   ShinyAPP to check f0 outliers, either by contour or point data: [InterVisual](https://k-li.shinyapps.io/InterVisual/)
-   ShinyAPP to visualise PCA results (from PCA scores to reconstructed contours): \[InterVisual-PCA\](<https://github.com/kc-li/InterVisual-fpca>)
-   Customized praat script facilitating checking process.

#### Current status ⏱️

-   processing the 7 people data

#### Next steps ☑️

-   2026 Late Feb & Early March: Get in touch with Tong & Yao: new dataset; update reasults; article plan

-   2026 April-May: Write the article

### Non-canonical Q Handbook chapter

-   A systematic review of the landscape. Questions inspired through working on the chapter:



#### Completed ✅

-   2024 Aug-Oct: Syntax, semantics writing
-   2025 Jan-Apr: recording, prosody, first draft sent out
-   2025 Sep: new materials and recording, prosody
-   2025 Dec - 2026 Jan: second draft revising and sent out

#### Current status ⏱️

-   Waiting for the second round review

#### Next steps ☑️

- Finalising

### Non-canonical Q Experiment

-   Focus: Investigate how prosody reflects subtle contextual differences across subtypes of question intonation, and how these interact with different morpho-syntactic forms.


#### Completed ✅

-   2025 July-August: Shumian visit, initiate the paln

-   2025 August-November: Experiment materials, online implementation and pilot

#### Current status ⏱️

- A auditory rating 

#### Next steps ☑️

- 2026 Feb: auditory rating experiment materials; set up
- 2026 Mar: rating experiment
- 2026 Apr-May: production data collection
- 2026 Jun-Aug: production data analysis and plan

### Mandarin question in corpus

- Investigate tone–intonation interactions in spontaneous speech, as well as the question usages (morphosyntactic vs. prosodic) in real life. 

#### Completed ✅

- 2024 Nov: trial processing of MagicData corpus
- 2025 Mar-Jun: detailed cleaning and checking of corpus
- 2025 Sep-Oct: turn-taking processing; prosodic patterns of three SFPs, for Dag van de Fonetiek

#### Current status ⏱️
-   On hold





<!-- ## Project ideas -->

<!-- ### The role of intonation in word recognition -->

<!-- -   Tone recognition is relatively robust. To what extent does intonation influence lexical tone processing during word recognition? -->

<!--     -   Audio: 你看到的字是。/你看到的字是妈？\ -->
<!--         Visual World paradigm: 妈 麻 骂 猫\ -->
<!--         Judgment：which intonation do you hear? -->

<!--     -   Backround -->

<!--         -   Parallel activation: tone, intonation, and segmental information become available more or less simultaneously. -->

<!--         -   Immediate interaction, tone and intonation interact immediately -->

<!--         -   In Mandarin, tone processing easier and more robust than intonation ('intonation gives way to tone.') -->

<!--             -   higher accuracy -->

<!--             -   shorter reaction time -->

<!--         -   When tone and intonation are in conflict: Cantonese low tone & question intonation causes difficulty in processing, whereas Mandarin T4 & question makes it easier to process -->

<!-- -   **Speaker variability:** How do listeners cope with variation in intonation realization across speakers? Can they correctly decode a speaker’s communicative intention—even upon first encounter? -->

<!--     -   Introduce at least 2 speakers voice (especially w.r.t. T4 strategy) -->

<!-- -   **Predictive context:** Does contextual information help listeners anticipate upcoming intonation? In natural speech, listeners often infer whether a speaker is likely to ask for information or provide it. Knowing the likely intonational contour in advance may facilitate more accurate and faster lexical activation. -->

<!--     -   Expanding audio: 我想说，你看到的字是妈。/我想问，你看到的字是妈？ -->


<!-- ## My keywords -->

<!-- -   The psychological reality of semantic categories -->
<!-- -   Mental representation -->
<!-- -   Individual variation vs. normalisation -->
<!--     -   Individual difference is important - how did we achieve the meaning? -->
<!--     -   Think of the metaphor of perceiving a segment - -->


<!-- ### Non-canonical questions -->

<!-- -   Context setting: compared to rhetorical questions, where one or two sentences easily trigger the reading, biased questions contexts seem to be more difficult to trigger prosodic marking. This reflects: -->
<!--     -   In the biased questions contexts, speakers do not necessarily convey this context. Wherereas in rhetorical questions, speakers feel obliged to mark the rhetorical questions (indicating that I'm not really asking for infromation). In the biased questions, speakers may have less pressure to indicate what they've already known. -->
<!--     -   It could be that the biased question semantic framework is good for analytic clearance, but not really psychological reality. Therefore speakers found it difficult to process such information. -->
<!--     -   For the conflicting contexts (epistemicP_evidenceN, or epistemicN_evidenceP), the prosody is easy, is also due to the conflicting information seems to prompt the speakers to express them more. -->
<!-- -   Experiment setup -->
<!--     -   What is not ideal for Gorilla, is the potential risk of not collecting multiple response in one page. (Consult the support team) -->
<!--     -   Special usages of high/low negations -->
<!--     -   Bias effects are not independent form focus effects, especially verum focus. -->
